Python: true

engines:
  pep8:
    enabled: true
  duplication:
    enabled: true
    languages:
      - python:
          python_version: 3
  radon:
    enabled: true
    config:
      python_version: 3

ratings:
  path:
    - "ppm/**/*"
