sudo: false
language: python
python: '3.6'

install:
- pip install codeclimate-test-reporter

before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
- python -m unittest spec/*.py

notification:
  email:
    recipients: luiscmholanda@gmail.com
    on_success: never
    on_failure: always
